### ISSUE TITLE
[BUG] Singing version is v2 but has been recognized to v1

### ISSUE THREAD

**Issue by Goooler** [LibChecker/LibChecker#1193] opened 2024-04-30 06:43 UTC
### Checklist / 检查清单

- [X] No one has submitted a similar or identical bug report before. / 之前没有人提交过类似或相同的 bug report。
- [X] I'm using the latest version of LibChecker. / 我正在使用 LibChecker 的最新版本。

### LibChecker version / LibChecker 版本

Latest release / 最新稳定版

### Bug description / Bug 描述

<img width="330" alt="image" src="https://github.com/LibChecker/LibChecker/assets/10363352/ffc31d6c-2192-4884-9183-5c825f978a1d">

```
./apksigner verify -v /Users/goooler/Downloads/my-release.apk

Verifies
Verified using v1 scheme (JAR signing): true
Verified using v2 scheme (APK Signature Scheme v2): true
Verified using v3 scheme (APK Signature Scheme v3): false
Verified using v3.1 scheme (APK Signature Scheme v3.1): false
Verified using v4 scheme (APK Signature Scheme v4): false
Verified for SourceStamp: false
Number of signers: 1
WARNING: META-INF/com/android/build/gradle/app-metadata.properties not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
WARNING: META-INF/CHANGES not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
WARNING: META-INF/README not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
WARNING: META-INF/README.md not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
WARNING: META-INF/services/Ii1iii111i.iiI1 not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
WARNING: META-INF/services/iI1iI11.i1I1iIIi111 not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
WARNING: META-INF/services/java.nio.charset.spi.CharsetProvider not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
```

### Expected behavior / 预期行为

It should be v2.

### Actual behavior / 实际行为

V1 is here.

### UI / OS

Pixel

### Android Version / Android 版本

A14

**Comment by zhaobozhen** [comment] 2024-04-30 08:10
Duplicate of #1115

**Closed as not planned** 2024-04-30 08:14 UTC
Labels: bug
